site_name: Docs for ATRI
repo_url: https://github.com/Kyomotoi/ATRI
repo_name: Kyomotoi/ATRI
edit_uri: "https://github.com/Kyomotoi/Project-ATRI-Docs/tree/main/docs"
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Kyomotoi/ATRI
      name: test
  analytics:
    provider: google
    property: G-8FY5XX5ZG3
  generator: false
copyright: Copyright © 2022 Kyomotoi All Rights Reserved.

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - 主页: index.md
  - 关于: about.md
  - 部署项目:
    - 准备工作: install/installation.md
    - 直接部署: install/install-direct.md
    - 配置本项目: install/configuration-bot.md
    - 使用 Docker 部署: install/install-via-docker.md 
    - 第一次对话: install/helloworld.md
  - 服务介绍:
    - 概览: user/overview.md
    - 基础服务-机器人管理: user/service-manager.md
    - 基础服务-机器人帮助: user/service-help.md
    - 基础服务-机器人状态: user/service-status.md
    - 基础服务-用户反馈: user/service-repo.md
    - 基础服务-基础功能: user/service-essential.md
    - 基础服务-广播: user/service-broadcast.md
    - 服务-kimo: user/service-kimo.md
    - 服务-在线运行代码: user/service-coderunner.md
    - 服务-乐: user/service-funny.md
    - 服务-小程序检测: user/service-applet.md
    - 服务-以图搜图: user/service-saucenao.md
    - 服务-涩图: user/service-setu.md
    - 服务-小工具: user/service-util.md
    - 服务-群老婆: user/service-wife.md
    - 服务-以图搜番: user/service-animesearch.md
    - 服务-B站动态推送: user/service-bilibili_dynamic.md
    - 服务-拍立得: user/service-polaroid.md
    - 服务-控制台: user/service-console.md
    - 服务-Twitter动态订阅: user/service-twitter.md
  - 开发 - 贡献:
    - 概览: developer/overview.md
  - 时间线: changelog.md
