name: Auto gen build
on:
  push:
    branches:
      - main
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.5"
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
